# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build


# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 build:
    name: python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, 3.10.12]
        mpi: ['mpich', 'openmpi']
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
     
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}
      - run: mpicc helloworld.c -o helloworld
      - run: mpiexec -n 2 ./helloworld
      
      - name: Install dependencies
        uses: actions/setup-python@v3 
        with:                                                                                                                                                                                              
           python-version: ${{ matrix.python-version }}  
      - run: python -m pip install --upgrade pip
        
      - name: Install mpi4py
        uses: actions/setup-python@v3 
        with:                                                                                                                                                                                              
           python-version: ${{ matrix.python-version }} 
      - run: python -m pip install mpi4py
      
      - name: Test mpi4py
        uses: actions/setup-python@v3 
        with:                                                                                                                                                                                              
           python-version: ${{ matrix.python-version }} 
      - run: mpiexec -n 4 python -m mpi4py.futures multi_mpi_exe.py
      - run: mpirun -np 4 --oversubscribe python -m mpi4py.futures
